Explode archives in temp folder, Promote archiver package version to v3.2.2
jfrog/jfrog-client-go pull request #208
Opened 2020-09-30 23:01 UTC by barbelity

2020-12-12 10:03 UTC, eyalbe4 requested changes
We should add tests for extractions of both zip and tar.gz formats.

2020-12-12 10:03 UTC, eyalbe4 commented on utils/io/fileutils/files.go
> +// Copy directory content from one path to another.
Copy --> Move

2020-12-13 16:47 UTC, barbelity commented on httpclient/client.go
> +	isSupportedArchive := fileutils.IsSupportedArchive(flags.FileName)
Removed the redundant check.

2020-12-13 16:48 UTC, barbelity commented on httpclient/client.go
>  	log.Info(logMsgPrefix+"Extracting archive:", flags.FileName, "to", extractionPath)
Removed the redundant log message.

2020-12-13 16:49 UTC, barbelity commented on utils/io/fileutils/files.go
> +// Copy directory content from one path to another.
Fixed.

2020-12-13 17:52 UTC, merged