Added detailed summary support for upload command
jfrog/jfrog-client-go pull request #213
Opened 2020-10-15 14:29 UTC by talarian1

Related: https://github.com/jfrog/jfrog-cli-core/pull/23.

2020-10-15 14:53 UTC, talarian1 commented
I have read the CLA Document and I hereby sign the CLA

2020-10-21 15:42 UTC, eyalbe4 requested changes

2020-10-21 15:42 UTC, eyalbe4 commented on artifactory/services/upload.go
> +func (us *UploadService) createArtifactHandlerFunc(uploadResult *utils.Result, uploadParams UploadParams) artifactContext {
It looks like the following local variables used in the function, do nor need to be declared implicitly. They can be created when returned from the functions returning them:
```
			var uploaded bool
			var target string
			var artifactFileInfo utils.FileInfo
```

2020-10-21 15:42 UTC, eyalbe4 commented on artifactory/services/upload.go
> +		err = us.ResultWriter.Close()
It makes more sense not to close the ```ResultWriter``` here. The function that creates it (```UploadFilesWithResultReader```) should be the one that closes with defer.
The same should be done in the download flow, in the ```performTasks``` method, in download.go.
This approach is not always possible, but I think it is good practice to stick to this approach when possible (if you opened it? You'll close it :)).

2020-10-26 13:43 UTC, merged