New general progress indication bar
jfrog/jfrog-client-go pull request #236
Opened 2020-12-01 13:37 UTC by talarian1

- [x] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2020-12-02 11:42 UTC, RobiNino requested changes
Looks great!

2020-12-02 11:42 UTC, RobiNino commented on httpclient/client.go
> +		reader, ok = progressReader.ActionWithProgress(reqContent).(io.Reader)
the ok check can probably be removed if ActionWithProgress is changed (here and in similar places)

2020-12-07 09:45 UTC, eyalbe4 requested changes

2020-12-07 09:45 UTC, eyalbe4 commented on utils/io/progress.go
> +	AddNewReplacementSpinner(replaceId int, prefix, extraInformation string) (id int)
Let's change this API to a more generic. I suggest naming it *StateChanged*.

2020-12-07 09:45 UTC, eyalbe4 commented on utils/io/progress.go
> +	GetProgressBar(id int) (bar ProgressBar)
Let's rename to *GetProgress*.

2020-12-07 09:45 UTC, eyalbe4 commented on utils/io/progress.go
>  	Abort(id int)
I suggest renaming *Abort(id int)* to *RemoveProgress(id int)*.

2020-12-07 09:45 UTC, eyalbe4 commented on utils/io/progress.go
> +	// Increases the general progress bar total count by given n.
// Increases the general progress bar total count by given n. --> // Increments the general progress total count by given n.

2020-12-07 09:45 UTC, eyalbe4 commented on utils/io/progressbar.go
> +type ProgressBar interface {
I suggest moving this interface into *progress.go*, together with *ProgressMgr* intefface.
Let's also rename it to *Progress* and remove the word "Bar" from its comments and methods.

2020-12-07 09:45 UTC, eyalbe4 commented on utils/io/progressbar.go
> +	// Aborts a progress indication. Called on both successful and unsuccessful operations
indication --> indicator

2020-12-08 13:22 UTC, eyalbe4 requested changes

2020-12-08 13:22 UTC, eyalbe4 commented on utils/io/progress.go
> +	// Initializes a new reader progress indication for a new file transfer.
indication --> indicator

2020-12-08 13:22 UTC, eyalbe4 commented on utils/io/progress.go
> +	// Uses to updated the progress indicator progress.
Uses to updated... --> Used for updating...

2020-12-13 10:46 UTC, merged