Parallel move and copy commands
jfrog/jfrog-client-go pull request #248
Opened 2020-12-13 12:20 UTC by barbelity

- [ ] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----

2020-12-13 17:01 UTC, eyalbe4 requested changes

2020-12-14 18:06 UTC, barbelity commented on artifactory/services/utils/searchutil.go
> +	recordType := recordValue.Type()
Fixed.

2020-12-14 18:10 UTC, barbelity commented on artifactory/services/movecopy.go
> +		defer tempAggregatedReader.Close()
Removed the redundant Close().

2020-12-14 18:16 UTC, barbelity commented on artifactory/services/movecopy.go
> +		moveReader, err := mc.getPathsToMove(moveSpec)
All moveReaders are being closed by the defer func() few lines above.

2020-12-14 18:16 UTC, barbelity commented on artifactory/services/movecopy.go
> +// Receive multiple 'ReaderSpecTuple' items and merge them into a single 'ContentReader' of 'MoveResultItem'.
Changed.

2020-12-14 18:18 UTC, barbelity commented on artifactory/services/movecopy.go
> +	length, err := reader.Length()
The length is being used for logging how many artifacts are actually going to be moved/copied.
Should we remove this log message?

2020-12-14 18:19 UTC, barbelity commented on artifactory/services/movecopy.go
> +func (mc *MoveCopyService) parallelMoveFiles(reader *content.ContentReader, params []MoveCopyParams) (successCount, failedCount int, err error) {
Changed.

2020-12-14 18:19 UTC, barbelity commented on artifactory/services/movecopy.go
> +func (mc *MoveCopyService) createFileMoveCopyHandlerFunc(result *utils.Result) fileMoveCopyHandlerFunc {
Changed.

2020-12-14 18:20 UTC, barbelity commented on artifactory/services/movecopy.go
> +func (mc *MoveCopyService) moveFile(sourcePath, destPath, logMsgPrefix string) (bool, error) {
Changed.

2020-12-14 18:46 UTC, barbelity commented on artifactory/services/movecopy.go
> +func (mc *MoveCopyService) MoveCopyServiceMoveFilesWrapper(moveSpecs ...MoveCopyParams) (successCount, failedCount int, err error) {
Changed.

2020-12-14 19:26 UTC, eyalbe4 commented on artifactory/services/movecopy.go
> +		moveReader, err := mc.getPathsToMove(moveSpec)
OK.

2020-12-14 19:28 UTC, eyalbe4 commented on artifactory/services/movecopy.go
> +	length, err := reader.Length()
Let's keep the log message, but avoid calling the Length() method. It doesn't really matters if the log message includes ```artifact``` or ```artifacts```. Let's have always ```artifacts``` regardless of the length.

2020-12-14 21:28 UTC, barbelity commented on artifactory/services/movecopy.go
> +	length, err := reader.Length()
We agreed to keep the log printing.
Opening https://github.com/jfrog/jfrog-client-go/issues/252 for improving the Length() performance.

2020-12-14 21:29 UTC, merged