Fix download explode for windows
jfrog/jfrog-client-go pull request #323
Opened 2021-04-01 08:36 UTC by gailazar300

- [x] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2021-04-01 11:51 UTC, RobiNino requested changes
I suggest fixing the comparison in `ExtractArchive` along this fix to be on the safe side, since `GetFileAndDirFromPath` is widely used and might experience some changes.

2021-04-07 10:36 UTC, RobiNino requested changes

2021-04-07 15:08 UTC, merged

2021-04-14 14:54 UTC, kenth0120 commented
When will this PR be merged into the main branch and deployed to AZDO marketplace?

2021-04-14 16:45 UTC, eyalbe4 commented
@kenth0120,
The initial plan was to deliver this fix to Azure DevOps by the end of this week, along with a few other fixes and improvements. 
Since however we understand this fix is really needed as soon as possible, let us try to carefully cherry pick this fix into it's own JFrog CLI patch, and then release a patch for the Azure DevOps extension, with the JFrog CLI upgrade only. 
I'll share another update here.