feat: use Build info to create release bundle
jfrog/jfrog-client-go pull request #354
Opened 2021-05-26 14:10 UTC by sguiheux

I noticed that ArtifactoryCommonParams.Build is never use during the creation of a release bundle.
I use the "same" code as Bundle parameter. Works fine :)

2021-05-28 09:51 UTC, yahavi requested changes
@sguiheux 
Thanks for this pull request!
The `CreateAqlBodyForSpecWithPattern` function is widely used by other use cases. For example, when you run a search command with pattern and build, for performance-wise, we run 2 AQL queries - the one in `CreateAqlBodyForSpecWithPattern`,  and [another one](https://github.com/jfrog/jfrog-client-go/blob/v0.23.1/artifactory/services/utils/aqlquerybuilder.go#L103) to filter the results by the input build. 
If you want, you can track the flow of [SearchBySpecWithPattern](https://github.com/jfrog/jfrog-client-go/blob/v0.23.1/artifactory/services/utils/searchutil.go#L161).

Here you have a special use case whereby you have no choice but to put all filters in only 1 AQL. Therefore I think we should be careful when adding the build Artifacts to this AQL and make sure that only in the release bundles specific use case they will be added to the AQL generated by `CreateAqlBodyForSpecWithPattern`. 

Please let me know if there is anything unclear.

2021-06-14 08:02 UTC, sguiheux commented
Hi, sorry for the delay.
I understand, but not sure to know how to fix this :/

2021-06-14 08:08 UTC, sguiheux commented
It's strange to have a method to create a something from an input, and you cannot use all the input because it can break something.
Maybe the input is not the good one, and we must have 2 functions no?

2022-01-25 15:16 UTC, eyalbe4 commented
@sguiheux - 
We unintentionally abandoned this discussion a few minths ago.
Would you like to share some info about the use case? Are you still interested in promoting this?

2023-12-11 15:33 UTC, closed without merging