README Tests section improvements
jfrog/jfrog-client-go pull request #423
Opened 2021-08-28 14:08 UTC by eyalbe4

- [x] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----
- Added ```-timeout 0``` options to the tests command.
- Modified the *Tests* section formating and structure.

2021-09-02 06:52 UTC, yahavi requested changes

2021-09-02 06:52 UTC, yahavi commented on README.md
>  To run tests on the source code, you'll need a running JFrog Artifactory Pro instance.
Artifactory Pro for Artifactory tests
Xray for the Xray tests
Distribution and an Enterprise+ license for Distribution tests

2021-09-02 06:52 UTC, yahavi commented on README.md
> +### Flags
To avoid confusion with the Go flags
```suggestion
### Authentication Flags
```

2021-09-02 06:52 UTC, yahavi commented on README.md
>  | `-access.url`        | [Optional] JFrog Access URL.                                                                           |
I suggest moving the `-access.url` up, to be with the other URLs.

2021-09-02 06:52 UTC, yahavi commented on README.md
> +go test -v github.com/jfrog/jfrog-client-go/tests -timeout 0 -run TestGetArtifactoryVersionWithCustomHttpClient [test-types] [flags]
```suggestion
go test -v github.com/jfrog/jfrog-client-go/tests -timeout 0 -run TestGetArtifactoryVersionWithCustomHttpClient -test.artifactory -rt.url=http://127.0.0.1:8081/artifactory -rt.user=admin -rt.password=password
```

2021-09-07 05:46 UTC, eyalbe4 commented
Great feedback @yahavi. Implemented all.

2021-09-07 05:46 UTC, merged