Build-Scan v2
jfrog/jfrog-client-go pull request #474
Opened 2021-11-22 08:30 UTC by sverdlov93

- [ ] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----
New build scan command that works directly with Xray.

2021-11-28 08:36 UTC, eyalbe4 requested changes
I'd love to review this PR again following the upcoming changes,

2021-11-28 08:36 UTC, eyalbe4 commented on xray/services/buildscan.go
> +	ticker := time.NewTicker(defaultSyncSleepInterval)
It looks to me that this waiting mechanis, with the ticker is more compex that it should be.
Why don't we just have a loop with a fixed number of iterations (which is the wait timeout actually) and a 5 seconds sleep inside it. We also don't need to spawn a new go routine for it.

2021-11-28 08:36 UTC, eyalbe4 commented on xray/services/summary.go
> +func (ss *SummaryService) GetXrayDetails() auth.ServiceDetails {
This method seem to be unused.

2021-11-28 08:36 UTC, eyalbe4 commented on xray/services/summary.go
> +func (ss *SummaryService) GetArtifactSummary(artifactSummaryRequest ArtifactSummaryRequest) (*SummaryResponse, error) {
I suggest we remove this API, becuase it's unclear when it should be used.
Let's also remove the structs this API uses.

2021-11-28 08:36 UTC, eyalbe4 commented on xray/manager.go
> +// BuildScan will send Xray the given build for scan
// BuildScan will send Xray the given build for scan
-->
// BuildScan scans a published build-info with Xray.

2021-11-28 08:36 UTC, eyalbe4 commented on xray/manager.go
> +// BuildSummary will get the build summary from Xray
BuildSummary will get the build summary from Xray
-->
BuildSummary returns the a summary of build scan which had been previously performed.

2021-11-29 16:07 UTC, sverdlov93 commented on xray/services/buildscan.go
> +	log.Info(buildScanInfo)
it log from xray about the status of the scan

2021-11-30 08:03 UTC, merged