convert omitempty boolean params to pointers
jfrog/jfrog-client-go pull request #485
Opened 2021-12-02 16:14 UTC by sverdlov93

Signed-off-by: sverdlov93 <sverdlov93@gmail.com>

- [ ] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----

2021-12-11 15:42 UTC, joeh90 commented on tests/utils_test.go
> +	RtPassword = flag.String("rt.password", "Jfrog-12", "Artifactory password")
Guessing these values were left in accidentally?

2021-12-11 15:42 UTC, joeh90 commented on tests/utils_test.go
> +	RtUrl = flag.String("rt.url", "https://ecosysjfrog.jfrog.io/artifactory/", "Artifactory url")
same as below

2021-12-11 17:05 UTC, sverdlov93 commented on tests/utils_test.go
> +	RtUrl = flag.String("rt.url", "https://ecosysjfrog.jfrog.io/artifactory/", "Artifactory url")
Removed. Thanks for noticing @joeh90

2021-12-11 22:08 UTC, eyalbe4 requested changes
We may also need to change the relevant README example following this change.

2021-12-19 16:46 UTC, eyalbe4 approved these changes

2021-12-20 08:51 UTC, merged