Improve executor logs
jfrog/jfrog-client-go pull request #511
Opened 2022-01-20 15:14 UTC by sverdlov93

- [ ] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----
Improve retry executor logs format for graph scan API pollings.
![Screen Shot 2022-01-20 at 17 08 59](https://user-images.githubusercontent.com/29822394/150366227-88578e1f-c4c2-4fd7-b264-c6253672152e.png)

2022-01-23 07:33 UTC, talarian1 approved these changes

2022-01-30 07:21 UTC, eyalbe4 requested changes

2022-01-30 07:21 UTC, eyalbe4 commented on utils/retryexecutor.go
> +		message := runner.getLogRetryMessage(i+1, err)
The logging logic is currently splinted between this place and the ```getLogRetryMessage``` function. I suggest mering everything into one function, that will do everything, named ```logRetry```. This shouls make the code reading easier.

2022-01-30 07:21 UTC, eyalbe4 commented on xray/services/scan.go
> +		MsgPrefix:       "Get Dependency Scan results... ",
Dependency --> Dependencies

2022-01-30 07:35 UTC, merged