Removed ability for the Logger to be nil and require a panic
jfrog/jfrog-client-go pull request #566
Opened 2022-05-10 22:47 UTC by onetwopunch

- [x] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-client-go/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2022-05-11 01:27 UTC, onetwopunch commented
I have read the CLA Document and I hereby sign the CLA

2022-05-12 15:43 UTC, onetwopunch commented
@yahavi @eyalbe4 any chance for a review on this? The failing test seems to be unrelated to the code I changed.

2022-05-15 11:27 UTC, eyalbe4 requested changes

2022-05-15 11:27 UTC, eyalbe4 commented on utils/log/logger.go
> +var DefaultLogger = NewLogger(INFO, nil)
It looks like DefaultLogger can be made private.
DefaultLogger --> defaultLogger

2022-05-17 18:19 UTC, eyalbe4 approved these changes

2022-05-17 18:20 UTC, merged