Add git call to find .git directory for git worktrees
jfrog/jfrog-client-go pull request #605
Opened 2022-06-23 20:29 UTC by Robert-Morgowicz

Adds a new section to handleSubmoduleIfNeeded which queries git for the git dir if it's in a worktree instead of failing to find the config.  

- [x] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-client-go/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----

closes https://github.com/jfrog/jfrog-cli/issues/1531

2022-06-23 20:31 UTC, Robert-Morgowicz commented
I have read the CLA Document and I hereby sign the CLA

2022-07-10 15:35 UTC, eyalbe4 commented
@Robert-Morgowicz,
I see that you're using `exec.Command("git", "rev-parse", "--git-dir")` as a fallback, but that brings the following question - 
What if the code used only this git command in the first place? Wouldn't it always work? Do we still need the code that runs before it? 
If not, will you be able to share more information about the two cases?

2022-07-14 10:20 UTC, eyalbe4 commented
Got it @Robert-Morgowicz.
In that case. I think we better have only the git command approach, and remove the older code. The code would be simpler and more predicable. We should also see iof there's a test that covers this, and if not, add the test.

2022-08-08 19:50 UTC, Robert-Morgowicz commented
> Got it @Robert-Morgowicz. In that case. I think we better have only the git command approach, and remove the older code. The code would be simpler and more predicable. We should also see iof there's a test that covers this, and if not, add the test.

I reduced it to just using the new implementation (asking git for the location of the .git dir).  I tested it and it works for submodules as well.  I couldn't figure out how to add a test for git worktrees, though.  I see where to add one in `utils/vcsdetails_test.go`, but digging into `utils/tests/utils.go`, I don't see where the actual git calls used to create these test repos are coming from.

2022-08-15 04:29 UTC, eyalbe4 commented
Thank you @Robert-Morgowicz.
Here's how you can testing for the submodules functionality you added.
The `handleSubmoduleIfNeeded` function you improved is called from the `ReadConfig` function,
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/7830056/184576394-98f7308f-e9fb-47da-962e-85b14667f642.png">

The `ReadConfig` function is tested by the `testReadConfig` function.
<img width="493" alt="image" src="https://user-images.githubusercontent.com/7830056/184576508-ebb6d7c5-578e-49b4-bc52-c5fc018e1ace.png">

If you look at the first line of this test function, you'll see that it calls the `getDotGitPath(t)` function, which returns a path to a .git directory for the testing. This .git directory is copied to from the `testdata` directory.
You can take the same approach, and create a new `testReadConfigWithSubmodules` function, which worls similarly like the existing `testReadConfig` function. You can place your own submodules .git inside the tests data, and your new test function can copy and test it test it.

2022-10-12 15:33 UTC, lex-ibm commented
recheck

2022-10-18 15:20 UTC, lex-ibm commented
Hello @eyalbe4!

We've added a test case for worktrees. Is there anything else we need to do?

2022-11-01 16:08 UTC, lex-ibm commented
Ping

2022-11-01 18:30 UTC, eyalbe4 commented
Let me review this soon @lex-ibm.

2022-11-21 14:51 UTC, notoriousUdo commented
Any updates here?

2022-11-23 15:29 UTC, eyalbe4 requested changes

2022-11-23 15:29 UTC, eyalbe4 commented on utils/git.go
> +	// worktreePathReduced := filepath.Dir(filepath.Dir(worktreePath))
The above two commented lines seem unclear / unnecessary.

2022-11-23 15:29 UTC, eyalbe4 commented on utils/git.go
> +	ResolvedGitPath := strings.TrimSpace(stdout.String())
ResolvedGitPath --> resolvedGitPath

2022-11-23 15:44 UTC, lex-ibm commented on utils/git.go
> +	ResolvedGitPath := strings.TrimSpace(stdout.String())
Refactored that variable name

2022-12-16 16:19 UTC, lex-ibm commented
Hey @eyalbe4! 
Happy holidays!

2023-01-13 17:43 UTC, schmidtl25 commented
Hi @eyalbe4 - can this PR be re-reviewed and merged?

2023-01-17 13:24 UTC, merged