Support reference tokens
jfrog/jfrog-client-go pull request #729
Opened 2023-04-01 16:17 UTC by mondo192

This change adds the missing field `include_reference_token` to the jfrog-go-client. This allows users to create aliases for access tokens as this was not possible with the client. Only the REST API.

Please see the associated open issue [here](https://github.com/jfrog/jfrog-client-go/issues/727) for more details.

- [x] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-client-go/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2023-04-04 16:09 UTC, yahavi requested changes
Thanks for this contribution @mondo192!
Please see my inline comments.

2023-04-04 16:09 UTC, yahavi commented on tests/accesstokens_test.go
> +	// Refernece token
```suggestion
	// Reference token
```

2023-04-04 16:09 UTC, yahavi commented on tests/accesstokens_test.go
> +	assert.NotEqual(t, token.IsReferenceToken, newToken.IsReferenceToken, "New reference token is identical to original one")
This fails the test. I'm not sure that the "include_reference_token" is included in the response from Xray.

https://github.com/jfrog/jfrog-client-go/actions/runs/4609825075/jobs/8147514091?pr=729#step:6:61

2023-04-05 08:57 UTC, yahavi requested changes
Just to be compatible with API. Change this and we'll merge.

2023-04-05 08:57 UTC, yahavi commented on auth/authutils.go
> +	IsReferenceToken *bool  `json:"include_reference_token,omitempty"`
```suggestion
	IncludeReferenceToken *bool  `json:"include_reference_token,omitempty"`
```

2023-04-06 09:37 UTC, yahavi approved these changes

2023-04-06 10:35 UTC, yahavi commented
Hi @mondo192,
After more thought, I made some changes to this PR - 
* Add `include_reference_token` **only** to CreateTokenParams
* Add the generated `reference_token` (ReferenceToken) to the response
* Allow RefreshAccessToken() to receive reference the include_reference_token flag
* Add test
* Document in the README

Please LMK what you think.

2023-04-17 09:33 UTC, eyalbe4 approved these changes

2023-04-18 15:42 UTC, merged