Add Username and Description to Access token commands
jfrog/jfrog-client-go pull request #759
Opened 2023-05-11 20:21 UTC by Smirl

# Summary

The new Access token APIs allow for a description and username to be set.

The description can be used to search for tokens once they are created. The username can be used by admins to create tokens on behalf of other users, or to create temporary users that belong to a group.

This PR also adds these two existing methods to the README.

## Fixes and helps some issues

closes #739
closes #727 (already there but issue still open, this now documents this in the README)
Might help with #753 as description can now be added.

2023-05-11 20:24 UTC, Smirl commented
I have read the CLA Document and I hereby sign the CLA

recheck

2023-05-11 20:28 UTC, Smirl commented
I have read the CLA Document and I hereby sign the CLA

2023-05-12 10:30 UTC, Smirl commented
Hi @yahavi 

Quick PR (with a follow up that I will rebase after this is merged). Thanks!

2023-06-01 10:14 UTC, Smirl commented
Hi @yahavi @sverdlov93 

I have rebased this to get it back up to date with dev. Let me know if you have any comments 😄

2023-07-20 07:59 UTC, eyalbe4 requested changes
Let's resolve the conflicts.

2023-08-31 11:16 UTC, eyalbe4 commented
@Smirl,
Are you planning to continue promoting this PR?

2023-08-31 11:21 UTC, eyalbe4 commented
Oh - I see now that https://github.com/jfrog/jfrog-client-go/pull/810 is meant to replace this PR.

2023-09-03 08:50 UTC, Smirl commented
Sorry for the delayed reply I hadn't checked in on this PR for a while. I can make the changes to the README on Monday.

2023-09-04 21:17 UTC, Smirl commented on README.md
> +#### Refresh an existing access token
Done

2023-09-04 21:17 UTC, Smirl commented on README.md
> +#### Create an access token for the JFrog Platform
Updated, thank you for the review

2023-09-04 21:18 UTC, Smirl commented
@eyalbe4 I have added the changes you asked for. Sorry for the delay. Should close the duplicate #810

2023-11-22 13:53 UTC, eyalbe4 commented
@Smirl,
While looking at the conflicts this PR has with the `dev` branch, I saw that the `Username` and `Description` fields have already been added to the `dev` branch/ Is this PR still needed? 
![image](https://github.com/jfrog/jfrog-client-go/assets/7830056/a97823d3-7b3f-4f41-ae1f-b1e5b2706bde)

2023-11-29 10:04 UTC, Smirl commented
Closing as fixed in another PR

2023-11-29 10:04 UTC, closed without merging