Several API changes
jfrog/jfrog-client-go pull request #789
Opened 2023-06-26 05:20 UTC by gshaibi

- [ ] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-client-go/actions/workflows/analysis.yml) passed.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----

This PR demonstrates the following changes.

AccessManager changes:
- Add RevokeAccessToken method
- Add GetAccessTokens method
- Add TokenId and Username to CreateAccessToken request and response

Artifactory SecurityService changes:
- Add description field to CreateTokenParams

2023-06-26 05:26 UTC, gshaibi commented
I have read the CLA Document and I hereby sign the CLA

2023-07-24 11:27 UTC, eyalbe4 requested changes
Let's also add tests for the new `RevokeAccessToken` and `GetAccessTokens` APIs added.
You cam use a mock server similar to how its down in the `TestUploadFilesWithFailure` function.

2023-08-01 21:11 UTC, gshaibi commented
Hi @eyalbe4 , thanks for the review!
Unfortunately, I don't have much time and I'm not sure I'll be able to fix all the issues you mentioned, but still I'll answer your questions.

2023-08-01 21:12 UTC, gshaibi commented on artifactory/manager.go
> +	// Deprecated
From what I saw on JFrog's docs, this API is deprecated

2023-08-02 04:37 UTC, eyalbe4 commented
@gshaibi,
The most important piece for getting this PR merged is the missing tests. If you aren't able to continue working on this currently, let's close this PR for now and if possible in the future, resume the work.

2023-08-02 05:23 UTC, closed without merging