Introducing Workspaces into pipelines
jfrog/jfrog-client-go pull request #793
Opened 2023-07-02 05:34 UTC by bhanurp

- [ ] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-client-go/actions/workflows/analysis.yml) passed.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----

2023-11-07 12:16 UTC, yahavi requested changes
@bhanurp 
Good work!
I reviewed your code and added some comments. I think a second round of code review is needed after fixing the issues.

Important - 
1. Ensure the tests are not failing
2. Add all new methods in manager.go to the README

2023-11-07 12:16 UTC, yahavi commented on pipelines/services/workspace.go
> +	uri, err := constructPipelinesURL(queryParams, ws.ServiceDetails.GetUrl(), stepConsolesAPI)
```suggestion
	uri, err := constructPipelinesURL(queryParams, ws.GetUrl(), stepConsolesAPI)
```

2023-11-07 12:16 UTC, yahavi commented on pipelines/services/workspace.go
> +	return consoles, err
```suggestion
	return consoles, errorutils.CheckError(err)
```

2023-11-07 12:16 UTC, yahavi commented on tests/pipelinesworkspaces_test.go
> +
```suggestion
```

2023-11-07 12:16 UTC, yahavi commented on tests/pipelinesworkspaces_test.go
> +	fmt.Printf("Bytes received : %s \n", pipelineRes)
```suggestion
```

2023-11-07 12:16 UTC, yahavi commented on tests/testdata/pip.yaml
Let's avoid using the word "pip" for JFrog pipelines in this and other JFrog CLI components. You can name this file "pipe".

2023-11-07 12:16 UTC, yahavi commented on tests/pipelinesworkspaces_test.go
> +	t.Run("test trigger pipelines workspace when resources are not valid", TestWorkspaceValidationWhenPipelinesResourcesAreNotValid)
```suggestion
	initPipelinesTest(t)
	t.Run("test trigger pipelines workspace when resources are not valid", TestWorkspaceValidationWhenPipelinesResourcesAreNotValid)
```

2023-11-07 12:23 UTC, yahavi commented on pipelines/services/validate.go
> +	log.Debug(string(data))
```suggestion
```

2023-11-07 12:24 UTC, yahavi commented on pipelines/services/validate.go
> +	headers["Content-Type"] = "application/json"
```suggestion
	utils.SetContentType("application/json", &headers)
```

2023-11-07 12:33 UTC, yahavi requested changes

2023-11-07 12:33 UTC, yahavi commented on pipelines/services/run.go
> +		log.Info(fmt.Sprintf("Triggered successfully\n%s %s \n%14s %s", "PipelineName :", pipeline, "Branch :", branch))
```suggestion
		log.Info(fmt.Sprintf("Triggered successfully\n%s %s \n%14s %s", "PipelineName:", pipeline, "Branch:", branch))
```

2023-11-07 12:33 UTC, yahavi commented on pipelines/services/types.go
> +
```suggestion
```

2023-11-07 12:33 UTC, yahavi commented on pipelines/services/validate.go
> +	httpDetails := vs.ServiceDetails.CreateHttpClientDetails()
```suggestion
	httpDetails := vs.CreateHttpClientDetails()
```

2023-11-07 12:33 UTC, yahavi commented on pipelines/services/validate.go
> +	m := make(map[string]string, 0)
What is "m"?

2023-11-07 12:33 UTC, yahavi commented on pipelines/services/validate.go
> +	}
You already check the status code in CheckResponseStatusWithBody. Please also consider nil before "CheckResponseStatusWithBody".

2023-11-07 12:33 UTC, yahavi commented on pipelines/services/validate.go
> +		return err
```suggestion
		return errorutils.CheckError(err)
```

2023-11-07 12:33 UTC, yahavi commented on pipelines/services/validate.go
> +		return errors.New("pipelines not found")
```suggestion
		return errorutils.CheckErrorf("pipelines not found")
```

2023-11-07 12:33 UTC, yahavi commented on pipelines/services/validate.go
> +			log.Info("Validation of pipeline resources completed successfully ")
```suggestion
			log.Info("Validation of pipeline resources completed successfully")
```

2023-11-07 12:33 UTC, yahavi commented on pipelines/services/validate.go
> +		log.Error("Failed to parse pipelines fetch run status url")
Please return an error here

2024-04-05 04:03 UTC, eyalbe4 commented
Closing this PR for now.

2024-04-05 04:03 UTC, closed without merging