Add distribution path mappings
jfrog/jfrog-client-go pull request #861
Opened 2023-11-14 10:21 UTC by YardenEdery

- [ ] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-client-go/actions/workflows/analysis.yml) passed.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----

2023-11-14 10:30 UTC, YardenEdery commented
I have read the CLA Document and I hereby sign the CLA

2023-11-14 10:41 UTC, Yarden-Edery commented
I have read the CLA Document and I hereby sign the CLA

2023-11-14 10:41 UTC, Yarden-Edery commented
recheck

2023-11-22 15:40 UTC, eyalbe4 commented
Thanks for creating this PR @YardenEdery!
Can you please add full description for this PR?

2023-11-22 16:09 UTC, eyalbe4 requested changes

2023-11-22 16:09 UTC, eyalbe4 commented on tests/distribution_test.go
> +	assert.Equal(t, 1, length)
The above code lines seem to be duplicated multiple times in this file. Let's move into a function and reuse the code.

2023-11-23 06:41 UTC, yahavi requested changes

2023-11-23 06:41 UTC, yahavi commented on tests/distribution_test.go
> +				ItemsFind: "{\"$or\":[{\"$and\":[{\"repo\":{\"$match\": \"" + strings.TrimSuffix(getRtTargetRepo(), "/") + "\"},\"name\":{\"$match\":\"b.in\"}}]}]}",
```suggestion
				ItemsFind: "{\"$or\":[{\"$and\":[{\"repo\":{\"$match\":\"" + strings.TrimSuffix(getRtTargetRepo(), "/") + "\"},\"name\":{\"$match\":\"b.in\"}}]}]}",
```

2023-11-23 06:41 UTC, yahavi commented on tests/distribution_test.go
> +				ItemsFind: "{\"$or\":[{\"$and\":[{\"repo\":{\"$match\": \"" + strings.TrimSuffix(getRtTargetRepo(), "/") + "\"},\"name\":{\"$match\":\"*.in\"}}]}]}",
```suggestion
				ItemsFind: "{\"$or\":[{\"$and\":[{\"repo\":{\"$match\":\"" + strings.TrimSuffix(getRtTargetRepo(), "/") + "\"},\"name\":{\"$match\":\"*.in\"}}]}]}",
```

2023-11-23 06:41 UTC, yahavi commented on tests/distribution_test.go
> +	if !assert.NoError(t, err) {
For better readability and shorter code, let's not use "ifs" in tests. The "assert" and/or "require" alone should help us to eliminate them.

2023-11-26 13:43 UTC, yahavi approved these changes
Well done @Yarden-Edery!
Thanks.

2023-11-26 13:44 UTC, merged