Remove SendScanGitInfoContext function call to cli-security package
jfrog/jfrog-client-go pull request #898
Opened 2024-02-04 10:08 UTC by orz25

- [ ] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-client-go/actions/workflows/analysis.yml) passed.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----

Remove SendScanGitInfoContext function call to cli-security package in order to have one multi scan id to multiple sca scans (we send a scan request per technology and we wish to associate all the scans to one multi scan id).

2024-02-04 13:56 UTC, eyalbe4 requested changes
Note that the *Static Analysis* check is failing.

2024-02-08 10:58 UTC, attiasas commented on xray/manager.go
> +func (sm *XrayServicesManager) SendXscGitInfoRequest(details *services.XscGitInfoContext) (multiScanId string, err error) {
please add comment explaning this request

2024-02-08 11:15 UTC, attiasas requested changes
Nice, take a look at my comments.
Please change the PR name to fit the changes of exposing new API.
Also add to the README the new changes of how to use it.

2024-02-11 08:41 UTC, orz25 commented on tests/xrayscan_test.go
> +var testXscVersion = "1.0.0"
Should I move also `gitInfoContextWithMinimalRequiredFields` and `gitInfoContextWithMissingFields`?

2024-02-11 09:10 UTC, attiasas commented on tests/xrayscan_test.go
> +var testXscVersion = "1.0.0"
@orz25, Yes all of the constants for tests are there you can see. see similar tests at the same file

2024-02-14 11:29 UTC, yahavi requested changes

2024-02-14 11:29 UTC, yahavi commented on tests/xrayscan_test.go
> +	}
```suggestion
        assert.NoError(t, err)
```

2024-02-14 11:29 UTC, yahavi commented on tests/xrayscan_test.go
> +	}
Let's use assert.Equals(t, ....)

2024-02-14 11:29 UTC, yahavi commented on tests/xrayscan_test.go
> +	}
Let's use assert.Equals(t, ....)

2024-02-14 11:29 UTC, yahavi commented on tests/xrayscan_test.go
> +	}
```suggestion
        assert.NoError(t, err)
```

2024-02-14 15:07 UTC, merged