Upload empty archive when all upload files were filtered out
jfrog/jfrog-client-go pull request #899
Opened 2024-02-05 09:21 UTC by sverdlov93

- [ ] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-client-go/actions/workflows/analysis.yml) passed.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----

2024-02-13 12:14 UTC, Or-Geva requested changes
I think we need to add a test for `JFROG_CLI_UPLOAD_EMPTY_ARCHIVE` flow.

2024-02-13 12:14 UTC, Or-Geva commented on artifactory/services/upload.go
> +	return false
```suggestion
	return len(paths) == 0 &&
		archive != "" &&
		strings.ToLower(os.Getenv("JFROG_CLI_UPLOAD_EMPTY_ARCHIVE")) == "true" 
```

2024-02-13 12:14 UTC, Or-Geva commented on artifactory/services/upload.go
> +	if shouldUploadAnEmptyArchive(uploadParams.Archive, paths) {
Let's move`uploadedDirs` to line 320 and add a log message that indicates JFROG_CLI_UPLOAD_EMPTY_ARCHIVE mode is detected

2024-02-13 12:15 UTC, Or-Geva commented on artifactory/services/upload.go
> +		strings.ToLower(os.Getenv("JFROG_CLI_UPLOAD_EMPTY_ARCHIVE")) == "true" {
Let's move `JFROG_CLI_UPLOAD_EMPTY_ARCHIVE` into const.

2024-02-14 09:02 UTC, sverdlov93 commented
> I think we need to add a test for `JFROG_CLI_UPLOAD_EMPTY_ARCHIVE` flow.
I added a test to JFrog CLI artifactory tests
@Or-Geva

2024-02-14 14:15 UTC, merged