add lifecycle support for bundle source type - artifacts
jfrog/jfrog-client-go pull request #903
Opened 2024-02-16 19:04 UTC by ns-kbhat

- [ ] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-client-go/actions/workflows/analysis.yml) passed.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----

2024-02-16 19:05 UTC, ns-kbhat commented
@yahavi need your help in review on merge of this. Appreciate prompt response and help to unblock on this feature.

2024-02-18 16:21 UTC, ns-kbhat commented
@RobiNino please check https://github.com/jfrog/jfrog-client-go/blob/1c352a93c23dcae0ef286e045854c68493af00c4/lifecycle/manager.go#L51

`lifecycle.RbPromotionParams` shows up as undefined.

2024-02-19 05:51 UTC, ns-kbhat commented
@yahavi @RobiNino merge conflicts with `dev` branch are now resolved.

Appreciate prompt review and subsequent release, so we can update our tooling. Thanks in advance!

2024-02-20 04:59 UTC, ns-kbhat commented
@yahavi @RobiNino when can I expect this PR to be reviewed?

I'm not clear what are the next steps for contributers - anything else required from my side?

2024-02-21 15:08 UTC, ns-kbhat commented
> Thanks for your contribution @ns-kbhat ! I'll go over your PR tomorrow.
> 
> Nothing else is required, I'll leave any comments as part of the CR.

@RobiNino did you have a chance to review today?

2024-02-21 16:01 UTC, RobiNino requested changes
Hi @ns-kbhat ,
Left a few comments, let me know if I can assist in any way.
Please run `go fmt` when you're done.
Thanks again!

2024-02-22 03:12 UTC, ns-kbhat commented on lifecycle/services/create.go
> +	SHA256 string `json:"sha256,omitempty"`
somehow I missed using `Add suggestion to batch` button, maybe I was too focussed on making and validating with an actual distribution.

Will use batch accept in future PRs.

2024-02-22 15:55 UTC, RobiNino approved these changes

2024-02-22 15:56 UTC, merged

2024-02-22 15:57 UTC, RobiNino commented
Much appreciated @ns-kbhat ! The changes will be included in our next release in the upcoming days