Artifactory Release Lifecycle Management - get lifecycle release bundle specification
jfrog/jfrog-client-go pull request #910
Opened 2024-02-24 16:21 UTC by ns-kbhat

- [ ] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-client-go/actions/workflows/analysis.yml) passed.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----

2024-02-24 16:21 UTC, ns-kbhat commented
@RobiNino please review.

2024-02-25 14:43 UTC, RobiNino requested changes
Thank you for another contribution @ns-kbhat !
Left a few minor comments on the code.

Since there is a lot of room for error in the parsing of this body, I suggest we add a unit test with a mock server in `lifecycle_test.go`. You can use the sample response from the [documentation](https://jfrog.com/help/r/jfrog-rest-apis/get-release-bundle-v2-version-specification).
Let me know if my assistance is required, thanks!

2024-02-25 14:43 UTC, RobiNino commented on lifecycle/manager.go
> +	return bs, err
```suggestion
	return rbService.GetReleaseBundleSpec(rbDetails)
```
I suggest to remove the unused `body` output from the function if it isn't used.

2024-02-25 14:43 UTC, RobiNino commented on lifecycle/services/status.go
> +			Value string `json:"value"`
```suggestion
			Values []string `json:"values"`
```

2024-02-25 18:44 UTC, ns-kbhat commented
> Thank you for another contribution @ns-kbhat ! Left a few minor comments on the code.
> 
> Since there is a lot of room for error in the parsing of this body, I suggest we add a unit test with a mock server in `lifecycle_test.go`. You can use the sample response from the [documentation](https://jfrog.com/help/r/jfrog-rest-apis/get-release-bundle-v2-version-specification). Let me know if my assistance is required, thanks!

@RobiNino added a test.
I don't use other source types yet, so I left them out of the spec type and checks.

2024-02-25 22:30 UTC, ns-kbhat commented
@RobiNino happened to notice an error in the `dev` branch.
Looks like signature change of `GetFileChecksums()` from `github.com/jfrog/build-info-go/utils` is breaking existing calls, please check or notify relevant owner.

2024-02-26 07:41 UTC, RobiNino approved these changes
Thank you @ns-kbhat !

2024-02-26 07:41 UTC, merged

2024-03-26 20:31 UTC, ns-kbhat commented
@RobiNino I keep getting failed workflow notification on this PR.

Is something pending that needs to be taken care of to close the PR correctly?

2024-03-27 07:46 UTC, RobiNino commented
@ns-kbhat For some reason every commit triggered a deployment that failed. 
Anyway, looks like the last one ended so you shouldn't receive any other notifications.
Sorry for the interruption!