Artifactory Release Lifecycle Management - Support release bundles deletion
jfrog/jfrog-client-go pull request #911
Opened 2024-02-25 13:36 UTC by RobiNino

- [x] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jfrog-client-go/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2024-03-04 16:01 UTC, eyalbe4 requested changes

2024-03-06 08:52 UTC, yahavi requested changes
Please add GetReleaseBundleVersionPromotions, DeleteReleaseBundleVersion and DeleteReleaseBundleVersionPromotion to the README.

Also, please add some unit tests.

2024-03-06 14:46 UTC, yahavi requested changes

2024-03-06 14:46 UTC, yahavi commented on lifecycle/services/delete.go
> +	err = errorutils.CheckResponseStatusWithBody(resp, body, http.StatusAccepted)
Let's add a debug logging with the server responses.

2024-03-06 14:46 UTC, yahavi commented on lifecycle/services/distribute.go
> +	err = errorutils.CheckError(json.Unmarshal(body, &distributionsResp))
Let's add a debug logging with the server responses.

2024-03-06 14:46 UTC, yahavi commented on lifecycle/services/promote.go
> +	err = errorutils.CheckError(json.Unmarshal(body, &response))
Let's add a debug logging with the server responses.

2024-03-17 16:06 UTC, merged